/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockButtons.h"

typedef struct _CMOCK_Buttons_CheckS5Switch_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ReturnVal;

} CMOCK_Buttons_CheckS5Switch_CALL_INSTANCE;

static struct MockButtonsInstance
{
  CMOCK_MEM_INDEX_TYPE Buttons_CheckS5Switch_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockButtons_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Buttons_CheckS5Switch_CallInstance, cmock_line, "Function 'Buttons_CheckS5Switch' called less times than expected.");
}

void MockButtons_Init(void)
{
  MockButtons_Destroy();
}

void MockButtons_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

char Buttons_CheckS5Switch(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Buttons_CheckS5Switch_CALL_INSTANCE* cmock_call_instance = (CMOCK_Buttons_CheckS5Switch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Buttons_CheckS5Switch_CallInstance);
  Mock.Buttons_CheckS5Switch_CallInstance = CMock_Guts_MemNext(Mock.Buttons_CheckS5Switch_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Buttons_CheckS5Switch' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void Buttons_CheckS5Switch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Buttons_CheckS5Switch_CALL_INSTANCE));
  CMOCK_Buttons_CheckS5Switch_CALL_INSTANCE* cmock_call_instance = (CMOCK_Buttons_CheckS5Switch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Buttons_CheckS5Switch_CallInstance = CMock_Guts_MemChain(Mock.Buttons_CheckS5Switch_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

