/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKS5CTRL_H
#define _MOCKS5CTRL_H

#include "S5Ctrl.h"

void MockS5Ctrl_Init(void);
void MockS5Ctrl_Destroy(void);
void MockS5Ctrl_Verify(void);




#define S5Ctrl_Silence_Expect() S5Ctrl_Silence_CMockExpect(__LINE__)
void S5Ctrl_Silence_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define S5Ctrl_SetFrequency_Expect(Frequency) S5Ctrl_SetFrequency_CMockExpect(__LINE__, Frequency)
void S5Ctrl_SetFrequency_CMockExpect(UNITY_LINE_TYPE cmock_line, int Frequency);
#define S5Ctrl_Loud_Expect() S5Ctrl_Loud_CMockExpect(__LINE__)
void S5Ctrl_Loud_CMockExpect(UNITY_LINE_TYPE cmock_line);

#endif
