/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockS5Ctrl.h"

typedef struct _CMOCK_S5Ctrl_Silence_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_S5Ctrl_Silence_CALL_INSTANCE;

static struct MockS5CtrlInstance
{
  CMOCK_MEM_INDEX_TYPE S5Ctrl_Silence_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockS5Ctrl_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.S5Ctrl_Silence_CallInstance, cmock_line, "Function 'S5Ctrl_Silence' called less times than expected.");
}

void MockS5Ctrl_Init(void)
{
  MockS5Ctrl_Destroy();
}

void MockS5Ctrl_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void S5Ctrl_Silence(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_S5Ctrl_Silence_CALL_INSTANCE* cmock_call_instance = (CMOCK_S5Ctrl_Silence_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.S5Ctrl_Silence_CallInstance);
  Mock.S5Ctrl_Silence_CallInstance = CMock_Guts_MemNext(Mock.S5Ctrl_Silence_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'S5Ctrl_Silence' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void S5Ctrl_Silence_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_S5Ctrl_Silence_CALL_INSTANCE));
  CMOCK_S5Ctrl_Silence_CALL_INSTANCE* cmock_call_instance = (CMOCK_S5Ctrl_Silence_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.S5Ctrl_Silence_CallInstance = CMock_Guts_MemChain(Mock.S5Ctrl_Silence_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

