/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKS5CTRL_H
#define _MOCKS5CTRL_H

#include "S5Ctrl.h"

void MockS5Ctrl_Init(void);
void MockS5Ctrl_Destroy(void);
void MockS5Ctrl_Verify(void);




#define S5Ctrl_Silence_Expect() S5Ctrl_Silence_CMockExpect(__LINE__)
void S5Ctrl_Silence_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define S5Ctrl_SetFrequency_ExpectAndReturn(Frequency, cmock_retval) S5Ctrl_SetFrequency_CMockExpectAndReturn(__LINE__, Frequency, cmock_retval)
void S5Ctrl_SetFrequency_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int Frequency, int cmock_to_return);
#define S5Ctrl_Loud_Expect() S5Ctrl_Loud_CMockExpect(__LINE__)
void S5Ctrl_Loud_CMockExpect(UNITY_LINE_TYPE cmock_line);

#endif
